name: Deploy to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.SARA }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
on:
  push:
    branches: main
    paths-ignore:
      - '**.md'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  



      - name: Install Vercel CLI
        run: npm install --global vercel
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}

      - name: Migrate DB
        run: pnpm --filter=./web/04-nextjs run db:migrate --config=drizzle-vercel.config.ts